Student grad home
philipangeloang/crs-client pull request #3
Opened 2023-10-30 06:46 UTC by mykahh

Accomplished
- [✓] Student Information
- [✓] Student Status Message
- [✓] Account Status
- [✓] Enlisted Classes

To be fixed in next PR:
- [ ] Color of Student Status Message (recent change of ui)
- [ ] Rounded border for table of Enlisted Classes

Observations:
- Date should be bold
- Time should be right-aligned (if strictly following ui)
- Home in navbar is not highlighted (red)
- No idea how to implement background image for PLM BG

2023-11-04 16:09 UTC, philipangeloang requested changes
Hi Mykah, can you revert back the app.tsx to its original state then repush this again. Save mo rin sa local mo yung changes mo sa app.tsx so that after pushing you can get it back.

This is needed to avoid merge conflicts. Make sure to re-push it again on the same branch as this one po. Thank you po

2023-11-14 11:19 UTC, mykahh commented
> e

nag git pull origin main me. sana wala ng conflict. di ko na kasi ma-revert so inupdate ko nalang.

2023-11-14 11:20 UTC, mykahh commented
> Hi Mykah, can you revert back the app.tsx to its original state then repush this again. Save mo rin sa local mo yung changes mo sa app.tsx so that after pushing you can get it back.
> 
> This is needed to avoid merge conflicts. Make sure to re-push it again on the same branch as this one po. Thank you po

nag git pull origin main me. sana wala ng conflict. di ko na kasi ma-revert so inupdate ko nalang.

2023-11-14 16:26 UTC, philipangeloang approved these changes

2023-11-14 16:26 UTC, merged